/**
 * Boss-specific reward and collection-log items exposed as individual bingo tasks.
 * Names follow the OSRS Wiki boss collection-log tables so artwork redirects and
 * organizer searches remain predictable. Drop-rate/KPH assumptions stay editable
 * in the maker and are intentionally omitted when the source has variable rolls.
 */
export const OSRS_BOSS_UNIQUE_GROUPS = [
  ['Barrows', "Ahrim's hood|Ahrim's robetop|Ahrim's robeskirt|Ahrim's staff|Karil's coif|Karil's leathertop|Karil's leatherskirt|Karil's crossbow|Dharok's helm|Dharok's platebody|Dharok's platelegs|Dharok's greataxe|Guthan's helm|Guthan's platebody|Guthan's chainskirt|Guthan's warspear|Torag's helm|Torag's platebody|Torag's platelegs|Torag's hammers|Verac's helm|Verac's brassard|Verac's plateskirt|Verac's flail"],
  ['Scurrius', "Scurrius' spine|Scurry"],
  ['Giant Mole', 'Baby Mole|Immaculate mole skin'],
  ['Deranged Archaeologist', 'Steel ring'],
  ['Dagannoth Supreme', 'Pet Dagannoth Supreme|Archers ring|Dragon axe|Seercull'],
  ['Dagannoth Rex', 'Pet Dagannoth Rex|Berserker ring|Warrior ring|Dragon axe'],
  ['Dagannoth Prime', 'Pet Dagannoth Prime|Seers ring|Dragon axe|Mud battlestaff'],
  ['Sarachnis', 'Sraracha|Jar of Eyes|Giant egg sac|Sarachnis cudgel|Pristine spider silk'],
  ['Blood Moon', 'Blood moon helm|Blood moon chestplate|Blood moon tassets|Dual macuahuitl'],
  ['Blue Moon', 'Blue moon helm|Blue moon chestplate|Blue moon tassets|Blue moon spear'],
  ['Eclipse Moon', 'Eclipse moon helm|Eclipse moon chestplate|Eclipse moon tassets|Eclipse atlatl'],
  ['Kalphite Queen', 'Kalphite Princess|Kq head|Jar of Sand|Dragon chainbody|Dragon pickaxe'],
  ["Kree'arra", "Pet Kree'arra|Armadyl helmet|Armadyl chestplate|Armadyl chainskirt|Armadyl hilt|Godsword shard 1|Godsword shard 2|Godsword shard 3"],
  ['Commander Zilyana', "Pet Zilyana|Armadyl crossbow|Saradomin hilt|Saradomin sword|Saradomin's light|Godsword shard 1|Godsword shard 2|Godsword shard 3"],
  ['General Graardor', 'Pet General Graardor|Bandos chestplate|Bandos tassets|Bandos boots|Bandos hilt|Godsword shard 1|Godsword shard 2|Godsword shard 3'],
  ["K'ril Tsutsaroth", "Pet K'ril Tsutsaroth|Staff of the dead|Zamorakian spear|Steam battlestaff|Zamorak hilt|Godsword shard 1|Godsword shard 2|Godsword shard 3"],
  ['The Hueycoatl', 'Huberte|Dragon hunter wand|Hueycoatl hide|Tome of earth (empty)|Huasca seed'],
  ['Corporeal Beast', 'Pet dark core|Elysian sigil|Spectral sigil|Arcane sigil|Holy elixir|Spirit shield|Jar of spirits'],
  ['Nex', 'Nexling|Ancient hilt|Nihil horn|Zaryte vambraces|Torva full helm (damaged)|Torva platebody (damaged)|Torva platelegs (damaged)'],
  ['Chaos Fanatic', 'Pet Chaos Elemental|Odium shard 1|Malediction shard 1'],
  ['Crazy archaeologist', 'Odium shard 2|Malediction shard 2|Fedora'],
  ['Scorpia', "Scorpia's offspring|Odium shard 3|Malediction shard 3"],
  ['King Black Dragon', 'Prince Black Dragon|Kbd heads|Dragon pickaxe|Draconic visage'],
  ['Chaos Elemental', 'Pet Chaos Elemental|Dragon pickaxe'],
  ['Revenant maledictus', "Amulet of avarice|Craw's bow (u)|Thammaron's sceptre (u)|Viggora's chainmace (u)|Ancient crystal|Ancient relic"],
  ["Calvar'ion", "Vet'ion Jr.|Ring of the gods|Skull of Vet'ion|Voidwaker blade|Dragon pickaxe"],
  ['Spindel', 'Venenatis spiderling|Treasonous ring|Fangs of Venenatis|Voidwaker gem|Dragon pickaxe'],
  ['Artio', 'Callisto cub|Tyrannical ring|Claws of Callisto|Voidwaker hilt|Dragon pickaxe'],
  ['Brutus', 'Beef|Mooleta|Bottomless milk bucket (empty)|Cow slippers'],
  ['Obor', 'Hill giant club'],
  ['Bryophyta', "Bryophyta's essence"],
  ['Amoxliatl', 'Moxi|Glacial temotli|Pendant of Ates (inert)|Frozen tear'],
  ['Royal Titans', 'Bran|Deadeye prayer scroll|Mystic vigour prayer scroll|Fire element staff crown|Ice element staff crown|Giantsoul amulet'],
  ['Doom of Mokhaiotl', 'Dom|Avernic treads|Eye of Ayak (uncharged)|Mokhaiotl cloth|Mokhaiotl waystone|Demon tear'],
  ['Mad Angel', 'Aggy|Hallowfell|Jar of light|Ardeaglais teleport'],
  ['Zulrah', "Pet snakeling|Tanzanite mutagen|Magma mutagen|Jar of swamp|Magic fang|Serpentine visage|Tanzanite fang"],
  ['Vorkath', "Vorki|Vorkath's head|Draconic visage|Skeletal visage|Jar of decay|Dragonbone necklace"],
  ['Phantom Muspah', 'Muphin|Venator shard|Ancient icon|Charged ice'],
  ['Maggot King', 'Maggot marquess|Crimson kisten|Elder venator fang'],
  ['The Nightmare', "Little Nightmare|Inquisitor's mace|Inquisitor's great helm|Inquisitor's hauberk|Inquisitor's plateskirt|Nightmare staff|Volatile orb|Harmonised orb|Eldritch orb|Jar of dreams|Slepey tablet|Parasitic egg"],
  ['Yama', 'Yami|Soulflame horn|Oathplate helm|Oathplate chest|Oathplate legs|Oathplate shards|Barrel of demonic tallow|Forgotten lockbox|Dossier'],
  ['Duke Sucellus', "Virtus mask|Virtus robe top|Virtus robe bottom|Chromium ingot|Awakener's orb|Magus vestige|Eye of the Duke|Ice quartz|Frozen tablet|Baron"],
  ['The Leviathan', "Virtus mask|Virtus robe top|Virtus robe bottom|Chromium ingot|Awakener's orb|Venator vestige|Leviathan's lure|Smoke quartz|Scarred tablet|Lil'viathan"],
  ['The Whisperer', "Virtus mask|Virtus robe top|Virtus robe bottom|Chromium ingot|Awakener's orb|Bellator vestige|Siren's staff|Shadow quartz|Sirenic tablet|Wisp"],
  ['Vardorvis', "Virtus mask|Virtus robe top|Virtus robe bottom|Chromium ingot|Awakener's orb|Ultor vestige|Executioner's axe head|Blood quartz|Strangled tablet|Butch"],
  ['The Mimic', 'Ring of 3rd age'],
  ['Hespori', 'Bottomless compost bucket|Iasor seed|Kronos seed|Attas seed'],
  ['Skotizo', 'Skotos|Jar of darkness|Dark claw'],
  ['Shellbane gryphon', "Gull|Jar of feathers|Belle's folly (tarnished)|Gryphon feather"],
  ['Grotesque Guardians', 'Noon|Black tourmaline core|Granite gloves|Granite ring|Granite hammer|Jar of stone'],
  ['Abyssal Sire', 'Abyssal orphan|Unsired|Abyssal head|Bludgeon spine|Bludgeon claw|Bludgeon axon|Jar of miasma|Abyssal dagger'],
  ['Kraken', 'Pet Kraken|Kraken tentacle|Trident of the seas|Jar of dirt'],
  ['Cerberus', 'Hellpuppy|Eternal crystal|Pegasian crystal|Primordial crystal|Jar of souls|Smouldering stone'],
  ['Araxxor', 'Nid|Araxyte venom sac|Araxyte fang|Noxious point|Noxious blade|Noxious pommel|Araxyte head|Jar of venom'],
  ['Thermonuclear smoke devil', 'Pet smoke devil|Occult necklace|Smoke battlestaff|Jar of smoke'],
  ['Alchemical Hydra', "Ikkle Hydra|Hydra's claw|Hydra tail|Hydra leather|Hydra's fang|Hydra's eye|Hydra's heart|Jar of chemicals|Alchemical hydra heads"],
  ['Crystalline Hunllef', 'Youngllef|Crystal armour seed|Crystal weapon seed|Enhanced crystal weapon seed'],
  ['Corrupted Hunllef', 'Youngllef|Crystal armour seed|Crystal weapon seed|Enhanced crystal weapon seed'],
  ['TzTok-Jad', 'TzRek-Jad|Fire cape'],
  ['TzKal-Zuk', 'Jal-Nib-Rek|Infernal cape'],
  ['Sol Heredit', "Smol Heredit|Dizana's quiver (uncharged)|Sunfire fanatic cuirass|Sunfire fanatic chausses|Sunfire fanatic helm|Echo crystal|Tonalztics of Ralos (uncharged)"],
  ['Tempoross', 'Tiny tempor|Big harpoonfish|Spirit angler outfit|Tome of water (empty)|Tackle box|Fish barrel|Dragon harpoon'],
  ['Wintertodt', 'Phoenix|Tome of fire (empty)|Pyromancer outfit|Warm gloves|Bruma torch|Dragon axe'],
  ['Zalcano', 'Smolcano|Crystal tool seed|Zalcano shard'],
  ['Chambers of Xeric', 'Dexterous prayer scroll|Arcane prayer scroll|Twisted buckler|Dragon hunter crossbow|Dinh\'s bulwark|Ancestral hat|Ancestral robe top|Ancestral robe bottom|Dragon claws|Elder maul|Kodai insignia|Twisted bow|Olmlet|Metamorphic dust|Twisted ancestral colour kit'],
  ['Theatre of Blood', 'Avernic defender hilt|Ghrazi rapier|Sanguinesti staff (uncharged)|Justiciar faceguard|Justiciar chestguard|Justiciar legguards|Scythe of vitur (uncharged)|Lil\' zik'],
  ['Theatre of Blood: Hard Mode', 'Holy ornament kit|Sanguine ornament kit|Sanguine dust'],
  ['Tombs of Amascut', "Osmumten's fang|Lightbearer|Elidinis' ward|Masori mask|Masori body|Masori chaps|Tumeken's shadow (uncharged)|Tumeken's guardian|Thread of elidinis|Breach of the scarab|Eye of the corruptor|Jewel of the sun"],
] as const satisfies ReadonlyArray<readonly [boss: string, items: string]>;

export type OsrsBossUniqueDrop = { boss: string; item: string; sourceUrl: string };

export const OSRS_BOSS_UNIQUE_DROPS: OsrsBossUniqueDrop[] = OSRS_BOSS_UNIQUE_GROUPS.flatMap(([boss, items]) =>
  items.split('|').map((item) => ({
    boss,
    item,
    sourceUrl: `https://oldschool.runescape.wiki/w/${encodeURIComponent(boss.replace(/\s+/g, '_'))}`,
  })),
);
